#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "==> EdgeKit build"
uv run edgekit build

# Cache-refresh secret: Cloudflare Python Workers eksponerer kun [vars] i
# os.environ (ikke `wrangler secret`), så vi injicerer den som en var.
# Værdien gemmes lokalt i .edge-secret (ikke i git).
SECRET_FILE="$ROOT/.edge-secret"
if [ -n "${CACHE_REFRESH_SECRET:-}" ]; then
  printf '%s' "$CACHE_REFRESH_SECRET" > "$SECRET_FILE"
elif [ ! -f "$SECRET_FILE" ]; then
  openssl rand -hex 32 > "$SECRET_FILE"
fi
CACHE_REFRESH_SECRET="$(cat "$SECRET_FILE")"

# Feedback-sheet-webhook: samme mønster som CACHE_REFRESH_SECRET ovenfor.
# Værdien gemmes lokalt i .feedback-webhook (ikke i git).
WEBHOOK_FILE="$ROOT/.feedback-webhook"
if [ -n "${GOOGLE_SHEET_WEBHOOK_URL:-}" ]; then
  printf '%s' "$GOOGLE_SHEET_WEBHOOK_URL" > "$WEBHOOK_FILE"
fi
GOOGLE_SHEET_WEBHOOK_URL="$(cat "$WEBHOOK_FILE" 2>/dev/null || true)"

echo "==> dist/ output"
rm -rf dist
mkdir -p dist

cp -r build/edgekit/wrangler/. dist/
cp -r templates dist/python_modules/templates

# Statiske filer serveres direkte fra Cloudflares CDN under /static/*
# (bypasser worker'en helt → sparer requests + CPU på free-plan). De bundtes
# bevidst IKKE ind i selve Python-workeren (kun i dist/assets nedenfor) —
# duplikatet skubbede workeren over gratisplanens 3 MiB-grænse. Flask-ruten
# /static/<path> er stadig i koden, men rammes reelt aldrig i produktion.
mkdir -p dist/assets/static
cp -r static/. dist/assets/static/
cat > dist/assets/_headers << 'HEADERS'
/static/*
  Cache-Control: public, max-age=31536000, immutable
  X-Content-Type-Options: nosniff

/static/css/*
  Content-Type: text/css; charset=utf-8

/static/js/*
  Content-Type: application/javascript; charset=utf-8
HEADERS

printf '%s\n' '"""Autogenerated launcher for Wrangler Python Workers."""' 'from worker import *  # noqa: F403' \
  > dist/python_modules/_edgekit_entrypoint.py

cat > dist/wrangler.toml << WRANGLER
name = "madshopper"
main = "python_modules/_edgekit_entrypoint.py"
compatibility_date = "2026-07-03"
workers_dev = true
# edgekit 0.1.1 er bygget til den indbyggede Python-SDK. Den eksterne SDK blev
# default 2026-04-21, så uden dette flag fejler Cloudflares deploy-introspektion
# med "ModuleNotFoundError: No module named 'workers'".
compatibility_flags = ["python_workers", "disable_python_external_sdk"]

[assets]
directory = "assets"
binding = "STATIC"
run_worker_first = false

[[kv_namespaces]]
binding = "CACHE_KV"
id = "0e60bdf03ed4490cbfac5fa72c8adca5"

[[d1_databases]]
binding = "DB"
database_name = "madshopper"
database_id = "8a43b0d1-1733-4abe-ad71-aa9bde4d4d12"

# Gratis native rate limiting (fail-open i worker.py). Beskytter dyre stier
# mod misbrug uden at ramme normale brugere (cache-hits rammes ikke).
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 150, period = 60 }

[vars]
CLOUDFLARE_WORKERS = "1"
ENABLE_PRICE_DB = "0"
SUPABASE_URL = "https://oxzxingkbsnqzpmjtktr.supabase.co"
NEXT_PUBLIC_SUPABASE_URL = "https://oxzxingkbsnqzpmjtktr.supabase.co"
SUPABASE_KEY = "sb_publishable_Jt8N0XezmzfZJSzzSwBBKQ_uGbNoq8f"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_Jt8N0XezmzfZJSzzSwBBKQ_uGbNoq8f"
CACHE_REFRESH_SECRET = "${CACHE_REFRESH_SECRET}"
SITE_URL = "https://madshopper.dk"
GOOGLE_SHEET_WEBHOOK_URL = "${GOOGLE_SHEET_WEBHOOK_URL:-}"

[[routes]]
pattern = "madshopper.dk"
custom_domain = true

[[routes]]
pattern = "www.madshopper.dk"
custom_domain = true
WRANGLER

cp "$ROOT/_routes.json" dist/_routes.json

rm -rf dist/dist
echo "==> dist klar ($(du -sh dist | cut -f1))"
